name: build and publish
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.12.1

      - name: Install packages
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Deploy
        run: bash ./deploy.sh tools.glowbuzzer.com E24WSXGU0FILML
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
